# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\IndexController:
        autowire: true
        public: true  # Ajoutez cette ligne pour rendre le service public

    App\Controller\Admin\LoginController:
        tags: ['controller.service_arguments']

    App\Controller\Admin\MenuController:
        tags: ['controller.service_arguments']
